### ISSUE TITLE
Support for v17development/flarum-blog discussions

### ISSUE THREAD

**Issue by iamdarkle** [clarkwinkelmann/flarum-ext-bookmarks#2]
Following on from this issue here (https://github.com/v17development/flarum-blog/issues/145), I think it would be great to support this for the blog, as this extension uses the `DiscussionPage-nav` which in a blog post is not there as there is no way to add these discussions to the bookmarks.

**Comment by clarkwinkelmann** [comment]
Added in version 1.1.0
